//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.11 at 12:59:40 PM GMT 
//


package com.ericsson.nms.dg.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.nms.dg.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Database_QNAME = new QName("http://www.ericsson.com/dg", "database");
    private final static QName _DataSpread_QNAME = new QName("http://www.ericsson.com/rg", "data_spread");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.nms.dg.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadIntervalType }
     * 
     */
    public LoadIntervalType createLoadIntervalType() {
        return new LoadIntervalType();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link TableDefType }
     * 
     */
    public TableDefType createTableDefType() {
        return new TableDefType();
    }

    /**
     * Create an instance of {@link RowsPerLoadType }
     * 
     */
    public RowsPerLoadType createRowsPerLoadType() {
        return new RowsPerLoadType();
    }

    /**
     * Create an instance of {@link DataTypeType }
     * 
     */
    public DataTypeType createDataTypeType() {
        return new DataTypeType();
    }

    /**
     * Create an instance of {@link DataSpreadType }
     * 
     */
    public DataSpreadType createDataSpreadType() {
        return new DataSpreadType();
    }

    /**
     * Create an instance of {@link DatabaseType }
     * 
     */
    public DatabaseType createDatabaseType() {
        return new DatabaseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatabaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ericsson.com/dg", name = "database")
    public JAXBElement<DatabaseType> createDatabase(DatabaseType value) {
        return new JAXBElement<DatabaseType>(_Database_QNAME, DatabaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSpreadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ericsson.com/rg", name = "data_spread")
    public JAXBElement<DataSpreadType> createDataSpread(DataSpreadType value) {
        return new JAXBElement<DataSpreadType>(_DataSpread_QNAME, DataSpreadType.class, null, value);
    }

}
